### PR TITLE
v4.4.0

### PR DESCRIPTION
**Pull request by etripier**
## [4.4.0] - 2019.11.20
* [New] Add `transformRuntime` option (#60)

### CODE REVIEW

**Comment by etripier** [comment]
@lencioni Sorry, think I need a review here.

**Comment by ljharb** [comment]
The version seems published even tho this isn't merged?

**Comment by etripier** [comment]
Yes, unfortunately - I have the ability to publish the package, but I can't merge this PR or push to `master` to update the version without a review.

**Comment by ljharb** [comment]
Typically the publish is the last step, after the bump is merged and pushed, since the publish is the only irrevocable part.

I'd stamp, but maintainer permissions seem to be set up incorrectly ¯\\\_(ツ)_/¯

**Comment by etripier** [comment]
Gotcha, I'll keep that in mind next time I release a version (and hopefully, I won't have to 🤞).

**Pull request merged**
